# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createACCwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(767, 862)
        Dialog.setMinimumSize(QtCore.QSize(767, 862))
        Dialog.setMaximumSize(QtCore.QSize(767, 862))
        Dialog.setStyleSheet("#Dialog{border-image: url(:/images/images/Default_a_darkblue_themed_image_for_wallpaper_related_to_expen_2.jpg);}")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setContentsMargins(100, 100, 100, 100)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Statistics_frame = QtWidgets.QFrame(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Statistics_frame.sizePolicy().hasHeightForWidth())
        self.Statistics_frame.setSizePolicy(sizePolicy)
        self.Statistics_frame.setMinimumSize(QtCore.QSize(567, 263))
        self.Statistics_frame.setMaximumSize(QtCore.QSize(4960, 1800))
        self.Statistics_frame.setStyleSheet("*{background-color: rgba(28, 41, 72,150);\n"
"border-radius: 40px;\n"
"pading-left: 20px;\n"
"font: 8pt \"Century Gothic\";}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"QLineEdit{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"}\n"
"QPushButton{background-color: transparent;\n"
"border: 1px solid;\n"
"border-color:#fff;\n"
"color:#fff;\n"
"border-radius: 9px;}")
        self.Statistics_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Statistics_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Statistics_frame.setLineWidth(0)
        self.Statistics_frame.setObjectName("Statistics_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.Statistics_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(33)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 86, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.Statistics_frame)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 8pt \"Century Gothic\";\n"
"background-color:transparent;")
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(37)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Name = QtWidgets.QLineEdit(self.Statistics_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Name.sizePolicy().hasHeightForWidth())
        self.Name.setSizePolicy(sizePolicy)
        self.Name.setMinimumSize(QtCore.QSize(214, 19))
        self.Name.setWhatsThis("")
        self.Name.setStyleSheet("border:1px solid;\n"
"border-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"background-color:transparent;")
        self.Name.setObjectName("Name")
        self.verticalLayout.addWidget(self.Name)
        self.amount_2 = QtWidgets.QLineEdit(self.Statistics_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amount_2.sizePolicy().hasHeightForWidth())
        self.amount_2.setSizePolicy(sizePolicy)
        self.amount_2.setMinimumSize(QtCore.QSize(214, 19))
        self.amount_2.setWhatsThis("")
        self.amount_2.setStyleSheet("border:1px solid;\n"
"border-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"background-color:transparent;")
        self.amount_2.setObjectName("amount_2")
        self.verticalLayout.addWidget(self.amount_2)
        self.amount_3 = QtWidgets.QLineEdit(self.Statistics_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amount_3.sizePolicy().hasHeightForWidth())
        self.amount_3.setSizePolicy(sizePolicy)
        self.amount_3.setMinimumSize(QtCore.QSize(214, 19))
        self.amount_3.setWhatsThis("")
        self.amount_3.setStyleSheet("border:1px solid;\n"
"border-color:transparent;\n"
"color: rgb(255, 255, 255);\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"background-color:transparent;")
        self.amount_3.setObjectName("amount_3")
        self.verticalLayout.addWidget(self.amount_3)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem2 = QtWidgets.QSpacerItem(118, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_2.addItem(spacerItem3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem4 = QtWidgets.QSpacerItem(278, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem4)
        self.pushButton = QtWidgets.QPushButton(self.Statistics_frame)
        self.pushButton.setMinimumSize(QtCore.QSize(100, 25))
        self.pushButton.setStyleSheet("QPushButton:hover{\n"
"\n"
"color:rgb(22, 201, 236);\n"
"border-color:rgb(22, 201, 236);\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        spacerItem5 = QtWidgets.QSpacerItem(123, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem5)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem6 = QtWidgets.QSpacerItem(20, 97, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem6)
        self.label.raise_()
        self.verticalLayout_3.addWidget(self.Statistics_frame)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Create Account</span></p></body></html>"))
        self.Name.setPlaceholderText(_translate("Dialog", "Name"))
        self.amount_2.setPlaceholderText(_translate("Dialog", "password"))
        self.amount_3.setPlaceholderText(_translate("Dialog", "repeat password"))
        self.pushButton.setText(_translate("Dialog", "Create"))
import imageresources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
