# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(908, 817)
        MainWindow.setMinimumSize(QtCore.QSize(818, 817))
        MainWindow.setMaximumSize(QtCore.QSize(908, 817))
        MainWindow.setStyleSheet("#centralwidget{\n"
"\n"
"    border-image: url(:/images/images/Default_a_darkblue_themed_image_for_wallpaper_related_to_expen_2.jpg);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(24)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMaximumSize(QtCore.QSize(553, 16777215))
        self.widget.setStyleSheet("#widget{\n"
"background-color: rgba(0,0,0,120);\n"
"border-radius:30px;\n"
"\n"
"}\n"
"QPushButton{\n"
"background-color:rgba(0,0,0,100);\n"
"color:#fff;\n"
"border-radius:10px;\n"
"padding:3px}\n"
"QPushButton:hover{\n"
"color:rgb(35, 197, 255);\n"
"background-color: rgba(0, 0, 0,200);\n"
"}\n"
"QLineEdit{\n"
"background-color:transparent;\n"
"border-radius:3px;\n"
"padding-left: 10px;\n"
"border:1px solid;\n"
"border-color:transparent;\n"
"border-bottom-color:rgb(104, 112, 166);\n"
"color:#fff;\n"
"}")
        self.widget.setObjectName("widget")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_9.setContentsMargins(40, 40, 40, 40)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.widget_4 = QtWidgets.QWidget(self.widget)
        self.widget_4.setStyleSheet("#widget_4{\n"
"background-color: rgba(42, 59, 102,160);\n"
"border-radius:30px;}")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_2.setSpacing(26)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(13, -1, 13, -1)
        self.horizontalLayout_11.setSpacing(10)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Usernamelabel_2 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Usernamelabel_2.setFont(font)
        self.Usernamelabel_2.setStyleSheet("color:#fff;\n"
"background-color:transparent;")
        self.Usernamelabel_2.setObjectName("Usernamelabel_2")
        self.horizontalLayout_11.addWidget(self.Usernamelabel_2)
        self.NameEntry_2 = QtWidgets.QLineEdit(self.widget_4)
        self.NameEntry_2.setMinimumSize(QtCore.QSize(302, 23))
        self.NameEntry_2.setStyleSheet("")
        self.NameEntry_2.setCursorPosition(0)
        self.NameEntry_2.setObjectName("NameEntry_2")
        self.horizontalLayout_11.addWidget(self.NameEntry_2)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(13, -1, 13, -1)
        self.horizontalLayout_12.setSpacing(9)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.passwordLabel_2 = QtWidgets.QLabel(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.passwordLabel_2.setFont(font)
        self.passwordLabel_2.setStyleSheet("color:#fff;\n"
"background-color:transparent;")
        self.passwordLabel_2.setObjectName("passwordLabel_2")
        self.horizontalLayout_12.addWidget(self.passwordLabel_2)
        self.Password_Entry_2 = QtWidgets.QLineEdit(self.widget_4)
        self.Password_Entry_2.setStyleSheet("")
        self.Password_Entry_2.setCursorPosition(0)
        self.Password_Entry_2.setObjectName("Password_Entry_2")
        self.horizontalLayout_12.addWidget(self.Password_Entry_2)
        self.verticalLayout.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        spacerItem = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_13.addItem(spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem1)
        self.loginButton_2 = QtWidgets.QPushButton(self.widget_4)
        self.loginButton_2.setMinimumSize(QtCore.QSize(141, 29))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loginButton_2.setFont(font)
        self.loginButton_2.setStyleSheet("")
        self.loginButton_2.setObjectName("loginButton_2")
        self.horizontalLayout_13.addWidget(self.loginButton_2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 200, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.horizontalLayout_13.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem4)
        self.forgotButton_2 = QtWidgets.QPushButton(self.widget_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.forgotButton_2.setFont(font)
        self.forgotButton_2.setStyleSheet("#forgotButton_2{background-color:transparent;\n"
"}")
        self.forgotButton_2.setObjectName("forgotButton_2")
        self.horizontalLayout_14.addWidget(self.forgotButton_2)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem6)
        self.createButton_2 = QtWidgets.QPushButton(self.widget_4)
        self.createButton_2.setMinimumSize(QtCore.QSize(100, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.createButton_2.setFont(font)
        self.createButton_2.setStyleSheet("#createButton_2{\n"
"background-color:transparent;}\n"
"")
        self.createButton_2.setObjectName("createButton_2")
        self.horizontalLayout_15.addWidget(self.createButton_2)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem7)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_9.addWidget(self.widget_4)
        self.horizontalLayout.addWidget(self.widget)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.loginlabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.loginlabel_2.setMinimumSize(QtCore.QSize(80, 40))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.loginlabel_2.setFont(font)
        self.loginlabel_2.setStyleSheet("#loginlabel_2{\n"
"background-color:transparent;\n"
"color:#fff;\n"
"padding:10px;\n"
"}")
        self.loginlabel_2.setObjectName("loginlabel_2")
        self.verticalLayout_3.addWidget(self.loginlabel_2)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem8 = QtWidgets.QSpacerItem(0, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem8)
        self.widget_6 = QtWidgets.QWidget(self.widget_3)
        self.widget_6.setMinimumSize(QtCore.QSize(191, 191))
        self.widget_6.setMaximumSize(QtCore.QSize(191, 191))
        self.widget_6.setStyleSheet("border:6px solid;\n"
"border-color: rgb(255, 255, 255);\n"
"\n"
"border-radius:95px")
        self.widget_6.setObjectName("widget_6")
        self.widget_5 = QtWidgets.QWidget(self.widget_6)
        self.widget_5.setGeometry(QtCore.QRect(5, -1, 181, 171))
        self.widget_5.setMinimumSize(QtCore.QSize(181, 171))
        self.widget_5.setMaximumSize(QtCore.QSize(181, 171))
        self.widget_5.setStyleSheet("image: url(:/icon/icons/user.svg);\n"
"border:none;")
        self.widget_5.setObjectName("widget_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(0, 168, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout_2.addItem(spacerItem9)
        spacerItem10 = QtWidgets.QSpacerItem(154, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.horizontalLayout_4.addWidget(self.widget_6)
        spacerItem11 = QtWidgets.QSpacerItem(32, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem11)
        self.verticalLayout_3.addWidget(self.widget_3)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_5.setContentsMargins(-1, 31, -1, -1)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.verticalLayout_3.addWidget(self.widget_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Usernamelabel_2.setText(_translate("MainWindow", "User name"))
        self.passwordLabel_2.setText(_translate("MainWindow", "Password  "))
        self.loginButton_2.setText(_translate("MainWindow", "Log In"))
        self.forgotButton_2.setText(_translate("MainWindow", "Forgot Password"))
        self.createButton_2.setText(_translate("MainWindow", "Create new"))
        self.loginlabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:18pt; font-weight:600;\">Log in to your </span></p><p><span style=\" font-size:18pt; font-weight:600;\">account</span></p></body></html>"))
import imageresources_rc
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
