# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HOMEWINDOW5.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from custom_widgets_classes import*


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1068, 850)
        MainWindow.setUnifiedTitleAndToolBarOnMac(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"    background-color: rgb(23, 34, 63);\n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(38, 56, 103);\n"
"}\n"
"QToolTip { \n"
"                           background-color: black; \n"
"                           color: white; \n"
"                           border: black solid 1px;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.leftmenu = QtWidgets.QHBoxLayout()
        self.leftmenu.setSpacing(0)
        self.leftmenu.setObjectName("leftmenu")
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setStyleSheet("QPushButton{\n"
"    border:none;\n"
"    color: rgb(119, 134, 172);\n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(38, 56, 103);\n"
"}\n"
"QPushButton:checked{\n"
"background-color:rgb(23, 34, 63);\n"
"}\n"
"*{\n"
"background-color: rgb(12, 20, 43);\n"
"}")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(7)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(12)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon = QtWidgets.QLabel(self.widget_2)
        self.icon.setMinimumSize(QtCore.QSize(31, 31))
        self.icon.setMaximumSize(QtCore.QSize(31, 31))
        self.icon.setStyleSheet("border-image: url(:/icon/icon2/alert-circle.svg);")
        self.icon.setText("")
        self.icon.setIndent(0)
        self.icon.setObjectName("icon")
        self.horizontalLayout.addWidget(self.icon)
        self.Expenzio = QtWidgets.QLabel(self.widget_2)
        self.Expenzio.setMinimumSize(QtCore.QSize(101, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.Expenzio.setFont(font)
        self.Expenzio.setStyleSheet("font: 75 12pt \"Century Gothic\";\n"
"color: rgb(255, 255, 255);")
        self.Expenzio.setTextFormat(QtCore.Qt.AutoText)
        self.Expenzio.setIndent(13)
        self.Expenzio.setObjectName("Expenzio")
        self.horizontalLayout.addWidget(self.Expenzio)
        self.verticalLayout_6.addLayout(self.horizontalLayout)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setContentsMargins(-1, 16, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Dashboard_Button = Button(self.widget_2)
        self.Dashboard_Button.setMinimumSize(QtCore.QSize(175, 60))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Dashboard_Button.setFont(font)
        self.Dashboard_Button.setToolTipDuration(-1)
        self.Dashboard_Button.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon2/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Dashboard_Button.setIcon(icon)
        self.Dashboard_Button.setIconSize(QtCore.QSize(25, 25))
        self.Dashboard_Button.setCheckable(True)
        self.Dashboard_Button.setChecked(False)
        self.Dashboard_Button.setAutoExclusive(True)
        self.Dashboard_Button.setObjectName("Dashboard_Button")
        self.verticalLayout_5.addWidget(self.Dashboard_Button)
        self.Wallets_Button = Button(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(7)
        sizePolicy.setHeightForWidth(self.Wallets_Button.sizePolicy().hasHeightForWidth())
        self.Wallets_Button.setSizePolicy(sizePolicy)
        self.Wallets_Button.setMinimumSize(QtCore.QSize(175, 60))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Wallets_Button.setFont(font)
        self.Wallets_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon2/credit-card.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Wallets_Button.setIcon(icon1)
        self.Wallets_Button.setIconSize(QtCore.QSize(25, 25))
        self.Wallets_Button.setCheckable(True)
        self.Wallets_Button.setChecked(False)
        self.Wallets_Button.setAutoExclusive(True)
        self.Wallets_Button.setAutoDefault(False)
        self.Wallets_Button.setDefault(False)
        self.Wallets_Button.setObjectName("Wallets_Button")
        self.verticalLayout_5.addWidget(self.Wallets_Button)
        self.CategoriesButton = Button(self.widget_2)
        self.CategoriesButton.setMinimumSize(QtCore.QSize(175, 60))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.CategoriesButton.setFont(font)
        self.CategoriesButton.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon2/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CategoriesButton.setIcon(icon2)
        self.CategoriesButton.setIconSize(QtCore.QSize(25, 25))
        self.CategoriesButton.setCheckable(True)
        self.CategoriesButton.setChecked(False)
        self.CategoriesButton.setAutoExclusive(True)
        self.CategoriesButton.setObjectName("CategoriesButton")
        self.verticalLayout_5.addWidget(self.CategoriesButton)
        self.Settings_Button = Button(self.widget_2)
        self.Settings_Button.setMinimumSize(QtCore.QSize(175, 60))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Settings_Button.setFont(font)
        self.Settings_Button.setToolTipDuration(-1)
        self.Settings_Button.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon2/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Settings_Button.setIcon(icon3)
        self.Settings_Button.setIconSize(QtCore.QSize(25, 25))
        self.Settings_Button.setCheckable(True)
        self.Settings_Button.setChecked(False)
        self.Settings_Button.setAutoExclusive(True)
        self.Settings_Button.setDefault(False)
        self.Settings_Button.setObjectName("Settings_Button")
        self.verticalLayout_5.addWidget(self.Settings_Button)
        spacerItem = QtWidgets.QSpacerItem(20, 539, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_6.addLayout(self.verticalLayout_5)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 11, -1, -1)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Help_Button = Button(self.widget_2)
        self.Help_Button.setMinimumSize(QtCore.QSize(140, 60))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Help_Button.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon2/help-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Help_Button.setIcon(icon4)
        self.Help_Button.setIconSize(QtCore.QSize(25, 25))
        self.Help_Button.setCheckable(True)
        self.Help_Button.setChecked(False)
        self.Help_Button.setAutoExclusive(True)
        self.Help_Button.setObjectName("Help_Button")
        self.verticalLayout_4.addWidget(self.Help_Button)
        self.Info_Button = Button(self.widget_2)
        self.Info_Button.setMinimumSize(QtCore.QSize(140, 60))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.Info_Button.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon2/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Info_Button.setIcon(icon5)
        self.Info_Button.setIconSize(QtCore.QSize(25, 25))
        self.Info_Button.setCheckable(True)
        self.Info_Button.setChecked(False)
        self.Info_Button.setAutoExclusive(True)
        self.Info_Button.setObjectName("Info_Button")
        self.verticalLayout_4.addWidget(self.Info_Button)
        self.verticalLayout_6.addLayout(self.verticalLayout_4)
        self.leftmenu.addWidget(self.widget_2)
        self.horizontalLayout_4.addLayout(self.leftmenu)
        self.mainwidget = QtWidgets.QWidget(self.centralwidget)
        self.mainwidget.setObjectName("mainwidget")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.mainwidget)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.widget_4 = QtWidgets.QWidget(self.mainwidget)
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget_4)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.MenuButton = QtWidgets.QPushButton(self.widget_4)
        self.MenuButton.setMinimumSize(QtCore.QSize(41, 41))
        self.MenuButton.setStyleSheet("background-color:transparent;")
        self.MenuButton.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icons/menu.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.MenuButton.setIcon(icon6)
        self.MenuButton.setIconSize(QtCore.QSize(24, 25))
        self.MenuButton.setCheckable(True)
        self.MenuButton.setChecked(False)
        self.MenuButton.setAutoExclusive(True)
        self.MenuButton.setObjectName("MenuButton")
        self.horizontalLayout_3.addWidget(self.MenuButton)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 5, 12, -1)
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.bellButton = QtWidgets.QPushButton(self.widget_4)
        self.bellButton.setMinimumSize(QtCore.QSize(36, 36))
        self.bellButton.setStyleSheet("background-color:transparent;")
        self.bellButton.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icons/bell.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.bellButton.setIcon(icon7)
        self.bellButton.setIconSize(QtCore.QSize(30, 30))
        self.bellButton.setObjectName("bellButton")
        self.horizontalLayout_2.addWidget(self.bellButton)
        self.accountButton = QtWidgets.QPushButton(self.widget_4)
        self.accountButton.setMinimumSize(QtCore.QSize(36, 36))
        self.accountButton.setStyleSheet("QPushButton{\n"
"    border: 1px solid;\n"
"    border-color:#fff;\n"
"    border-radius: 17px;\n"
"}\n"
"\n"
"font: 3pt \"Century Gothic\";")
        self.accountButton.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icons/user.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.accountButton.setIcon(icon8)
        self.accountButton.setIconSize(QtCore.QSize(25, 25))
        self.accountButton.setObjectName("accountButton")
        self.horizontalLayout_2.addWidget(self.accountButton)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addWidget(self.widget_4)
        self.changingwidget = QtWidgets.QStackedWidget(self.mainwidget)
        self.changingwidget.setStyleSheet("    background-color: rgb(23, 34, 63);")
        self.changingwidget.setObjectName("changingwidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_7 = QtWidgets.QLabel(self.page)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Century Gothic\";")
        self.label_7.setObjectName("label_7")
        self.verticalLayout_10.addWidget(self.label_7)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout_6.setContentsMargins(17, 29, 20, -1)
        self.horizontalLayout_6.setSpacing(20)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(31, -1, -1, 34)
        self.verticalLayout_9.setSpacing(20)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.overview_frame = custFrame(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overview_frame.sizePolicy().hasHeightForWidth())
        self.overview_frame.setSizePolicy(sizePolicy)
        self.overview_frame.setMinimumSize(QtCore.QSize(496, 180))
        self.overview_frame.setMaximumSize(QtCore.QSize(4960, 1800))
        self.overview_frame.setStyleSheet("*{background-color: rgb(28, 41, 72);\n"
"border-radius: 40px;\n"
"pading-left: 20px;}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"QLineEdit{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"}")
        self.overview_frame.setFrameShape(custFrame.NoFrame)
        self.overview_frame.setFrameShadow(custFrame.Plain)
        self.overview_frame.setLineWidth(0)
        self.overview_frame.setObjectName("overview_frame")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.overview_frame)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_3 = QtWidgets.QLabel(self.overview_frame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#fff")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_21.addWidget(self.label_3)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem2)
        self.widget_7 = QtWidgets.QWidget(self.overview_frame)
        self.widget_7.setObjectName("widget_7")
        self.verticalLayout_21.addWidget(self.widget_7)
        self.verticalLayout_9.addWidget(self.overview_frame)
        self.Statistics_frame = statframe(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Statistics_frame.sizePolicy().hasHeightForWidth())
        self.Statistics_frame.setSizePolicy(sizePolicy)
        self.Statistics_frame.setMinimumSize(QtCore.QSize(567, 263))
        self.Statistics_frame.setMaximumSize(QtCore.QSize(4960, 1800))
        self.Statistics_frame.setStyleSheet("*{background-color: rgb(28, 41, 72);\n"
"border-radius: 40px;\n"
"pading-left: 20px;}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"QLineEdit{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"}")
        self.Statistics_frame.setFrameShape(statframe.NoFrame)
        self.Statistics_frame.setFrameShadow(statframe.Plain)
        self.Statistics_frame.setLineWidth(0)
        self.Statistics_frame.setObjectName("Statistics_frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Statistics_frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setContentsMargins(30, 20, 30, -1)
        self.horizontalLayout_11.setSpacing(0)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_2 = QtWidgets.QLabel(self.Statistics_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setToolTipDuration(0)
        self.label_2.setStyleSheet("color:#fff")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_11.addWidget(self.label_2)
        spacerItem3 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem3)
        self.comboBox_3 = QtWidgets.QComboBox(self.Statistics_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_3.sizePolicy().hasHeightForWidth())
        self.comboBox_3.setSizePolicy(sizePolicy)
        self.comboBox_3.setMinimumSize(QtCore.QSize(111, 4))
        self.comboBox_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_3.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_3.setStyleSheet("*{color:#fff;\n"
"background-color: rgb(45, 63, 109);\n"
"border-radius:8px;}\n"
"QComboBox{\n"
"    padding-left: 20px;\n"
"\n"
"}\n"
"QComboBox::drop-down {\n"
"    \n"
"    image: url(:/icon/icons/chevron-down.svg);\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: none;\n"
"    padding: 3px\n"
"}\n"
"\n"
"")
        self.comboBox_3.setEditable(False)
        self.comboBox_3.setIconSize(QtCore.QSize(20, 20))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.horizontalLayout_11.addWidget(self.comboBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_11)
        self.widget_3 = QtWidgets.QWidget(self.Statistics_frame)
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout.addWidget(self.widget_3)
        self.verticalLayout_9.addWidget(self.Statistics_frame)
        self.Expense_Frame = custFrame(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Expense_Frame.sizePolicy().hasHeightForWidth())
        self.Expense_Frame.setSizePolicy(sizePolicy)
        self.Expense_Frame.setMinimumSize(QtCore.QSize(545, 219))
        self.Expense_Frame.setMaximumSize(QtCore.QSize(4960, 1800))
        self.Expense_Frame.setStyleSheet("*{background-color: rgb(28, 41, 72);\n"
"border-radius: 40px;\n"
"pading-left: 20px;}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"#amount,#description{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"border-bottom: 1px solid;\n"
"color: rgb(255, 255, 255);\n"
"border-color:rgba(255, 255, 255,100);\n"
"}\n"
"")
        self.Expense_Frame.setFrameShape(custFrame.NoFrame)
        self.Expense_Frame.setFrameShadow(custFrame.Plain)
        self.Expense_Frame.setLineWidth(0)
        self.Expense_Frame.setObjectName("Expense_Frame")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.Expense_Frame)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(-1, -1, 7, -1)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label = QtWidgets.QLabel(self.Expense_Frame)
        self.label.setMinimumSize(QtCore.QSize(141, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#fff")
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        spacerItem4 = QtWidgets.QSpacerItem(318, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.verticalLayout_12.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem5)
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(-1, -1, -1, 11)
        self.verticalLayout_11.setSpacing(18)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(6)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.group_ = QtWidgets.QComboBox(self.Expense_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.group_.sizePolicy().hasHeightForWidth())
        self.group_.setSizePolicy(sizePolicy)
        self.group_.setMinimumSize(QtCore.QSize(112, 4))
        self.group_.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.group_.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.group_.setFont(font)
        self.group_.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.group_.setStyleSheet("*{color:#fff;\n"
"background-color: rgb(45, 63, 109);\n"
"border-radius:8px;}\n"
"QComboBox{\n"
"    padding-left: 20px;\n"
"\n"
"}\n"
"QComboBox::drop-down {\n"
"    \n"
"    image: url(:/icon/icons/chevron-down.svg);\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: none;\n"
"    padding: 3px\n"
"}\n"
"\n"
"")
        self.group_.setEditable(False)
        self.group_.setCurrentText("")
        self.group_.setIconSize(QtCore.QSize(20, 20))
        self.group_.setObjectName("group_")
        self.group_.addItem("")
        self.group_.addItem("")
        self.horizontalLayout_5.addWidget(self.group_)
        self.amount = QtWidgets.QLineEdit(self.Expense_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amount.sizePolicy().hasHeightForWidth())
        self.amount.setSizePolicy(sizePolicy)
        self.amount.setMinimumSize(QtCore.QSize(214, 19))
        self.amount.setWhatsThis("")
        self.amount.setStyleSheet("")
        self.amount.setObjectName("amount")
        self.horizontalLayout_5.addWidget(self.amount)
        self.comboBox_2 = QtWidgets.QComboBox(self.Expense_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_2.sizePolicy().hasHeightForWidth())
        self.comboBox_2.setSizePolicy(sizePolicy)
        self.comboBox_2.setMinimumSize(QtCore.QSize(111, 4))
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_2.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_2.setStyleSheet("*{color:#fff;\n"
"background-color: rgb(45, 63, 109);\n"
"border-radius:8px;}\n"
"QComboBox{\n"
"    padding-left: 20px;\n"
"\n"
"}\n"
"QComboBox::drop-down {\n"
"    \n"
"    image: url(:/icon/icons/chevron-down.svg);\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: none;\n"
"    padding: 3px\n"
"}\n"
"\n"
"")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setIconSize(QtCore.QSize(20, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.horizontalLayout_5.addWidget(self.comboBox_2)
        self.verticalLayout_11.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(6)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem6 = QtWidgets.QSpacerItem(112, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem6)
        self.description = QtWidgets.QLineEdit(self.Expense_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.description.sizePolicy().hasHeightForWidth())
        self.description.setSizePolicy(sizePolicy)
        self.description.setMinimumSize(QtCore.QSize(214, 19))
        self.description.setStyleSheet("")
        self.description.setText("")
        self.description.setObjectName("description")
        self.horizontalLayout_8.addWidget(self.description)
        spacerItem7 = QtWidgets.QSpacerItem(111, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem7)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.pushButton = QtWidgets.QPushButton(self.Expense_Frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(90, 28))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border: 1px solid;\n"
"    border-color:#fff;\n"
"    border-radius: 7px;\n"
"color:#fff;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(22, 201, 236);\n"
"border-color:rgb(22, 201, 236);\n"
"}\n"
"font: 3pt \"Century Gothic\";")
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_9.addWidget(self.pushButton)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem9)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10.addLayout(self.verticalLayout_11)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem10)
        self.verticalLayout_12.addLayout(self.horizontalLayout_10)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.verticalLayout_9.addWidget(self.Expense_Frame)
        self.horizontalLayout_6.addLayout(self.verticalLayout_9)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, 2, -1, 34)
        self.verticalLayout_8.setSpacing(20)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Monthly_frame = custFrame(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Monthly_frame.sizePolicy().hasHeightForWidth())
        self.Monthly_frame.setSizePolicy(sizePolicy)
        self.Monthly_frame.setMinimumSize(QtCore.QSize(231, 305))
        self.Monthly_frame.setMaximumSize(QtCore.QSize(4420, 120000))
        self.Monthly_frame.setStyleSheet("*{background-color: rgb(28, 41, 72);\n"
"border-radius: 40px;\n"
"pading-left: 20px;}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"QLineEdit{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"}")
        self.Monthly_frame.setFrameShape(custFrame.NoFrame)
        self.Monthly_frame.setFrameShadow(custFrame.Plain)
        self.Monthly_frame.setLineWidth(0)
        self.Monthly_frame.setObjectName("Monthly_frame")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.Monthly_frame)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.label_5 = QtWidgets.QLabel(self.Monthly_frame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:#fff")
        self.label_5.setObjectName("label_5")
        self.verticalLayout_22.addWidget(self.label_5)
        self.widget_6 = QtWidgets.QWidget(self.Monthly_frame)
        self.widget_6.setObjectName("widget_6")
        self.verticalLayout_22.addWidget(self.widget_6)
        self.verticalLayout_8.addWidget(self.Monthly_frame)
        self.History_frame = custFrame(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.History_frame.sizePolicy().hasHeightForWidth())
        self.History_frame.setSizePolicy(sizePolicy)
        self.History_frame.setMinimumSize(QtCore.QSize(231, 355))
        self.History_frame.setMaximumSize(QtCore.QSize(23100, 35500))
        self.History_frame.setStyleSheet("*{background-color: rgb(28, 41, 72);\n"
"border-radius: 40px;\n"
"pading-left: 20px;}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"QLineEdit{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"}")
        self.History_frame.setFrameShape(custFrame.NoFrame)
        self.History_frame.setFrameShadow(custFrame.Plain)
        self.History_frame.setLineWidth(0)
        self.History_frame.setObjectName("History_frame")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.History_frame)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label_4 = QtWidgets.QLabel(self.History_frame)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:#fff")
        self.label_4.setObjectName("label_4")
        self.verticalLayout_23.addWidget(self.label_4)
        self.widget_5 = QtWidgets.QWidget(self.History_frame)
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_23.addWidget(self.widget_5)
        self.verticalLayout_8.addWidget(self.History_frame)
        self.horizontalLayout_6.addLayout(self.verticalLayout_8)
        self.verticalLayout_10.addLayout(self.horizontalLayout_6)
        self.changingwidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.label_8 = QtWidgets.QLabel(self.page_2)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Century Gothic\";")
        self.label_8.setObjectName("label_8")
        self.verticalLayout_20.addWidget(self.label_8)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(22, -1, -1, -1)
        self.horizontalLayout_22.setSpacing(20)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout()
        self.verticalLayout_18.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_18.setSpacing(6)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        spacerItem11 = QtWidgets.QSpacerItem(20, 93, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_18.addItem(spacerItem11)
        self.widget_10 = QtWidgets.QWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_10.sizePolicy().hasHeightForWidth())
        self.widget_10.setSizePolicy(sizePolicy)
        self.widget_10.setMinimumSize(QtCore.QSize(0, 51))
        self.widget_10.setObjectName("widget_10")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.widget_10)
        self.horizontalLayout_19.setContentsMargins(21, -1, 14, 0)
        self.horizontalLayout_19.setSpacing(0)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_13 = QtWidgets.QLabel(self.widget_10)
        self.label_13.setStyleSheet("color:rgb(255, 255, 255);\n"
"font: 9pt \"Century Gothic\";")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_19.addWidget(self.label_13)
        self.verticalLayout_17 = QtWidgets.QVBoxLayout()
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem12)
        self.pushButton_5 = QtWidgets.QPushButton(self.widget_10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(105, 28))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"    border: 1px solid;\n"
"    border-color:#fff;\n"
"    border-radius: 7px;\n"
"color:#fff;\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(22, 201, 236);\n"
"border-color:rgb(22, 201, 236);\n"
"}\n"
"font: 3pt \"Century Gothic\";")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_18.addWidget(self.pushButton_5)
        self.verticalLayout_17.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19.addLayout(self.verticalLayout_17)
        self.verticalLayout_18.addWidget(self.widget_10)
        spacerItem13 = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_18.addItem(spacerItem13)
        self.Monthly_frame_6 = QtWidgets.QFrame(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Monthly_frame_6.sizePolicy().hasHeightForWidth())
        self.Monthly_frame_6.setSizePolicy(sizePolicy)
        self.Monthly_frame_6.setMinimumSize(QtCore.QSize(100, 401))
        self.Monthly_frame_6.setMaximumSize(QtCore.QSize(4420, 120000))
        self.Monthly_frame_6.setStyleSheet("*{background-color: rgb(28, 41, 72);\n"
"border-radius: 40px;\n"
"pading-left: 20px;}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"QLineEdit{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"}")
        self.Monthly_frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Monthly_frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Monthly_frame_6.setLineWidth(0)
        self.Monthly_frame_6.setObjectName("Monthly_frame_6")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.Monthly_frame_6)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.scrollArea = QtWidgets.QScrollArea(self.Monthly_frame_6)
        self.scrollArea.setStyleSheet("")
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_16.addWidget(self.scrollArea)
        self.verticalLayout_18.addWidget(self.Monthly_frame_6)
        spacerItem14 = QtWidgets.QSpacerItem(20, 54, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_18.addItem(spacerItem14)
        self.horizontalLayout_22.addLayout(self.verticalLayout_18)
        self.widget_11 = QtWidgets.QWidget(self.page_2)
        self.widget_11.setObjectName("widget_11")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.widget_11)
        self.verticalLayout_19.setContentsMargins(-1, 0, 33, 0)
        self.verticalLayout_19.setSpacing(9)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setContentsMargins(-1, 20, -1, 20)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.overview_frame_6 = QtWidgets.QFrame(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overview_frame_6.sizePolicy().hasHeightForWidth())
        self.overview_frame_6.setSizePolicy(sizePolicy)
        self.overview_frame_6.setMinimumSize(QtCore.QSize(223, 107))
        self.overview_frame_6.setMaximumSize(QtCore.QSize(4960, 1800))
        self.overview_frame_6.setStyleSheet("*{background-color: rgb(28, 41, 72);\n"
"border-radius: 40px;\n"
"pading-left: 20px;}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"QLineEdit{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"}")
        self.overview_frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.overview_frame_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.overview_frame_6.setLineWidth(0)
        self.overview_frame_6.setObjectName("overview_frame_6")
        self.label_47 = QtWidgets.QLabel(self.overview_frame_6)
        self.label_47.setGeometry(QtCore.QRect(30, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("color:#fff")
        self.label_47.setObjectName("label_47")
        self.horizontalLayout_13.addWidget(self.overview_frame_6)
        spacerItem15 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem15)
        self.overview_frame_5 = QtWidgets.QFrame(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.overview_frame_5.sizePolicy().hasHeightForWidth())
        self.overview_frame_5.setSizePolicy(sizePolicy)
        self.overview_frame_5.setMinimumSize(QtCore.QSize(222, 107))
        self.overview_frame_5.setMaximumSize(QtCore.QSize(4960, 1800))
        self.overview_frame_5.setStyleSheet("*{background-color: rgb(28, 41, 72);\n"
"border-radius: 40px;\n"
"pading-left: 20px;}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"QLineEdit{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"}")
        self.overview_frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.overview_frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.overview_frame_5.setLineWidth(0)
        self.overview_frame_5.setObjectName("overview_frame_5")
        self.label_45 = QtWidgets.QLabel(self.overview_frame_5)
        self.label_45.setGeometry(QtCore.QRect(30, 20, 121, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("color:#fff")
        self.label_45.setObjectName("label_45")
        self.horizontalLayout_13.addWidget(self.overview_frame_5)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_13)
        self.verticalLayout_19.addLayout(self.horizontalLayout_21)
        self.Monthly_frame_5 = QtWidgets.QFrame(self.widget_11)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Monthly_frame_5.sizePolicy().hasHeightForWidth())
        self.Monthly_frame_5.setSizePolicy(sizePolicy)
        self.Monthly_frame_5.setMinimumSize(QtCore.QSize(100, 401))
        self.Monthly_frame_5.setMaximumSize(QtCore.QSize(4420, 120000))
        self.Monthly_frame_5.setStyleSheet("*{background-color: rgb(28, 41, 72);\n"
"border-radius: 40px;\n"
"pading-left: 20px;}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"QLineEdit{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"}")
        self.Monthly_frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Monthly_frame_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Monthly_frame_5.setLineWidth(0)
        self.Monthly_frame_5.setObjectName("Monthly_frame_5")
        self.label_46 = QtWidgets.QLabel(self.Monthly_frame_5)
        self.label_46.setGeometry(QtCore.QRect(30, 30, 92, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("color:#fff")
        self.label_46.setObjectName("label_46")
        self.verticalLayout_19.addWidget(self.Monthly_frame_5)
        spacerItem16 = QtWidgets.QSpacerItem(20, 54, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        self.verticalLayout_19.addItem(spacerItem16)
        self.horizontalLayout_22.addWidget(self.widget_11)
        self.verticalLayout_20.addLayout(self.horizontalLayout_22)
        self.changingwidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.label_9 = QtWidgets.QLabel(self.page_3)
        self.label_9.setGeometry(QtCore.QRect(20, 10, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Century Gothic\";")
        self.label_9.setObjectName("label_9")
        self.changingwidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_10 = QtWidgets.QLabel(self.page_4)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Century Gothic\";")
        self.label_10.setObjectName("label_10")
        self.verticalLayout_15.addWidget(self.label_10)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.widget_9 = QtWidgets.QWidget(self.page_4)
        self.widget_9.setObjectName("widget_9")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_9)
        self.verticalLayout_2.setContentsMargins(-1, -1, -1, 270)
        self.verticalLayout_2.setSpacing(30)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_6 = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color:#fff")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_12.addWidget(self.label_6)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem17)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.amount_2 = QtWidgets.QLineEdit(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.amount_2.sizePolicy().hasHeightForWidth())
        self.amount_2.setSizePolicy(sizePolicy)
        self.amount_2.setMinimumSize(QtCore.QSize(214, 26))
        self.amount_2.setWhatsThis("")
        self.amount_2.setStyleSheet("#amount_2{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"border-bottom: 1px solid;\n"
"color: rgb(255, 255, 255);\n"
"border-color:rgba(255, 255, 255,100);\n"
"}\n"
"    \n"
"    ")
        self.amount_2.setObjectName("amount_2")
        self.verticalLayout_2.addWidget(self.amount_2)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.yourwallets = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.yourwallets.setFont(font)
        self.yourwallets.setStyleSheet("color:#fff")
        self.yourwallets.setObjectName("yourwallets")
        self.horizontalLayout_14.addWidget(self.yourwallets)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem18)
        self.verticalLayout_2.addLayout(self.horizontalLayout_14)
        self.widget = QtWidgets.QWidget(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setObjectName("widget")
        self.verticalLayout_2.addWidget(self.widget)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.removeaccounts = QtWidgets.QLabel(self.widget_9)
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.removeaccounts.setFont(font)
        self.removeaccounts.setStyleSheet("color:#fff")
        self.removeaccounts.setObjectName("removeaccounts")
        self.horizontalLayout_15.addWidget(self.removeaccounts)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem19)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.removeaccount = Button(self.widget_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.removeaccount.sizePolicy().hasHeightForWidth())
        self.removeaccount.setSizePolicy(sizePolicy)
        self.removeaccount.setMinimumSize(QtCore.QSize(90, 28))
        self.removeaccount.setStyleSheet("QPushButton{\n"
"    border: 1px solid;\n"
"    border-color:#fff;\n"
"    border-radius: 7px;\n"
"    \n"
"    \n"
"    font: 75 11pt \"Century Gothic\";\n"
"    \n"
"    color: rgb(255, 255, 255);\n"
"    \n"
"    \n"
"    background-color: rgb(53, 79, 145);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:rgb(22, 201, 236);\n"
"border-color:rgb(22, 201, 236);\n"
"}\n"
"font: 3pt \"Century Gothic\";\n"
"")
        self.removeaccount.setObjectName("removeaccount")
        self.verticalLayout_2.addWidget(self.removeaccount)
        self.horizontalLayout_17.addWidget(self.widget_9)
        spacerItem20 = QtWidgets.QSpacerItem(11, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem20)
        self.widget_8 = QtWidgets.QWidget(self.page_4)
        self.widget_8.setObjectName("widget_8")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.widget_8)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem21 = QtWidgets.QSpacerItem(643, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem21)
        self.signout = Button(self.widget_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.signout.sizePolicy().hasHeightForWidth())
        self.signout.setSizePolicy(sizePolicy)
        self.signout.setMinimumSize(QtCore.QSize(90, 28))
        self.signout.setStyleSheet("QPushButton{\n"
"    border: 1px solid;\n"
"    border-color:#fff;\n"
"    border-radius: 7px;\n"
"    \n"
"    color: rgb(0, 0, 0);\n"
"    \n"
"    background-color: rgb(255, 255, 255);\n"
"    \n"
"    font: 75 8pt \"Century Gothic\";\n"
"}\n"
"QPushButton:hover{\n"
"color:rgb(22, 201, 236);\n"
"border-color:rgb(22, 201, 236);\n"
"}\n"
"")
        self.signout.setObjectName("signout")
        self.horizontalLayout_16.addWidget(self.signout)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem22)
        self.verticalLayout_3.addLayout(self.horizontalLayout_16)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem23)
        self.verticalLayout_14.addLayout(self.verticalLayout_3)
        self.horizontalLayout_17.addWidget(self.widget_8)
        self.verticalLayout_15.addLayout(self.horizontalLayout_17)
        self.changingwidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_11 = QtWidgets.QLabel(self.page_5)
        self.label_11.setGeometry(QtCore.QRect(10, 10, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Century Gothic\";")
        self.label_11.setObjectName("label_11")
        self.changingwidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.label_12 = QtWidgets.QLabel(self.page_6)
        self.label_12.setGeometry(QtCore.QRect(10, 10, 141, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(9)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: rgb(255, 255, 255);\n"
"\n"
"font: 75 12pt \"Century Gothic\";")
        self.label_12.setObjectName("label_12")
        self.changingwidget.addWidget(self.page_6)
        self.verticalLayout_7.addWidget(self.changingwidget)
        self.horizontalLayout_4.addWidget(self.mainwidget)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.changingwidget.setCurrentIndex(3)
        self.comboBox_3.setCurrentIndex(0)
        self.group_.setCurrentIndex(-1)
        self.comboBox_2.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Expenzio.setText(_translate("MainWindow", "Expenzio"))
        self.Dashboard_Button.setToolTip(_translate("MainWindow", "Go to home page"))
        self.Dashboard_Button.setText(_translate("MainWindow", "  Dashboard   "))
        self.Wallets_Button.setToolTip(_translate("MainWindow", "see wallets"))
        self.Wallets_Button.setText(_translate("MainWindow", "  Wallets          "))
        self.CategoriesButton.setToolTip(_translate("MainWindow", "category wise report "))
        self.CategoriesButton.setText(_translate("MainWindow", "  Categories   "))
        self.Settings_Button.setToolTip(_translate("MainWindow", "Open settings"))
        self.Settings_Button.setText(_translate("MainWindow", "  Settings        "))
        self.Help_Button.setToolTip(_translate("MainWindow", "Ask help"))
        self.Help_Button.setText(_translate("MainWindow", " Help                "))
        self.Info_Button.setToolTip(_translate("MainWindow", "About us"))
        self.Info_Button.setText(_translate("MainWindow", " Info                 "))
        self.label_7.setText(_translate("MainWindow", "  Dashboard"))
        self.label_3.setText(_translate("MainWindow", "   Overview"))
        self.label_2.setText(_translate("MainWindow", "Expense Statistics"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "Last 7 days"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Last month"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Last Year"))
        self.label.setText(_translate("MainWindow", "   Add Expenses"))
        self.group_.setItemText(0, _translate("MainWindow", "Item1"))
        self.group_.setItemText(1, _translate("MainWindow", "Item 2"))
        self.amount.setPlaceholderText(_translate("MainWindow", "Amount"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Item1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Item 2"))
        self.description.setPlaceholderText(_translate("MainWindow", "Description"))
        self.pushButton.setText(_translate("MainWindow", "Save"))
        self.label_5.setText(_translate("MainWindow", "This month"))
        self.label_4.setText(_translate("MainWindow", "History"))
        self.label_8.setText(_translate("MainWindow", "Wallets"))
        self.label_13.setText(_translate("MainWindow", "Transactions"))
        self.pushButton_5.setText(_translate("MainWindow", "Add Transaction"))
        self.label_47.setText(_translate("MainWindow", "Balance 2"))
        self.label_45.setText(_translate("MainWindow", "Balance"))
        self.label_46.setText(_translate("MainWindow", "This month"))
        self.label_9.setText(_translate("MainWindow", "Categories"))
        self.label_10.setText(_translate("MainWindow", "Settings"))
        self.label_6.setText(_translate("MainWindow", "Salary Day"))
        self.amount_2.setPlaceholderText(_translate("MainWindow", "Amount"))
        self.yourwallets.setText(_translate("MainWindow", "Your Wallets"))
        self.removeaccounts.setText(_translate("MainWindow", "Remove Accounts"))
        self.removeaccount.setText(_translate("MainWindow", "Remove Account"))
        self.signout.setText(_translate("MainWindow", "Sign Out"))
        self.label_11.setText(_translate("MainWindow", "Help"))
        self.label_12.setText(_translate("MainWindow", "Info"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
