# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'HOMEWINDOW2.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1063, 670)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("*{\n"
"    border:none;\n"
"    background-color:transparent;\n"
"    background:none;\n"
"    padding:0;\n"
"    margin:0;\n"
"    \n"
"    color: rgb(54, 61, 87);\n"
"}\n"
"#centralwidget{\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"#leftMenusubcontainer{\n"
"    \n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(12, 20, 43);\n"
"}\n"
"QPushButton{\n"
"    text-align:left;\n"
"    padding:2px 10px;\n"
"    color:#fff;\n"
"    \n"
"}\n"
"QPushButton:hover{\n"
"    \n"
"    \n"
"    background-color: rgb(38, 56, 103);\n"
"}\n"
"#exandinframe{\n"
"    \n"
"    background-color: rgb(25, 24, 84);\n"
"}\n"
"#MENUlabel{\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"#frame_6{\n"
"    \n"
"    background-color: rgb(23, 34, 63);\n"
"}\n"
"#frame_9{\n"
"    \n"
"    \n"
"    \n"
"    background-color: rgb(134, 62, 197);\n"
"}\n"
"#frame_4{\n"
"    \n"
"    background-color: rgb(25, 24, 84);\n"
"}\n"
"QProgressBar::chunk{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(0, 78, 163, 255), stop:1 rgba(255, 16, 164, 255));\n"
"border-radius:5px;\n"
"}\n"
"\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.leftMenuContainer = QtWidgets.QWidget(self.centralwidget)
        self.leftMenuContainer.setGeometry(QtCore.QRect(0, 0, 261, 671))
        self.leftMenuContainer.setObjectName("leftMenuContainer")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.leftMenuContainer)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftMenusubcontainer = QtWidgets.QWidget(self.leftMenuContainer)
        self.leftMenusubcontainer.setStyleSheet("QPushButton{\n"
"padding-left:30px;\n"
"    color: rgb(119, 134, 172);\n"
"}")
        self.leftMenusubcontainer.setObjectName("leftMenusubcontainer")
        self.frame_2 = QtWidgets.QFrame(self.leftMenusubcontainer)
        self.frame_2.setGeometry(QtCore.QRect(0, 50, 261, 181))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setStyleSheet("")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.Dashboard = QtWidgets.QPushButton(self.frame_2)
        self.Dashboard.setGeometry(QtCore.QRect(0, 10, 261, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.Dashboard.setFont(font)
        self.Dashboard.setToolTipDuration(1)
        self.Dashboard.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.Dashboard.setAutoFillBackground(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icon/icon2/home.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Dashboard.setIcon(icon)
        self.Dashboard.setIconSize(QtCore.QSize(20, 20))
        self.Dashboard.setObjectName("Dashboard")
        self.WalletsButton = QtWidgets.QPushButton(self.frame_2)
        self.WalletsButton.setGeometry(QtCore.QRect(0, 50, 261, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.WalletsButton.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon2/credit-card.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.WalletsButton.setIcon(icon1)
        self.WalletsButton.setIconSize(QtCore.QSize(20, 20))
        self.WalletsButton.setObjectName("WalletsButton")
        self.CategoriesButton = QtWidgets.QPushButton(self.frame_2)
        self.CategoriesButton.setGeometry(QtCore.QRect(0, 90, 261, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.CategoriesButton.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon2/folder.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.CategoriesButton.setIcon(icon2)
        self.CategoriesButton.setIconSize(QtCore.QSize(20, 20))
        self.CategoriesButton.setObjectName("CategoriesButton")
        self.SettingsButton = QtWidgets.QPushButton(self.frame_2)
        self.SettingsButton.setGeometry(QtCore.QRect(0, 130, 261, 28))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.SettingsButton.setFont(font)
        self.SettingsButton.setToolTipDuration(-1)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon2/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.SettingsButton.setIcon(icon3)
        self.SettingsButton.setIconSize(QtCore.QSize(20, 20))
        self.SettingsButton.setObjectName("SettingsButton")
        self.frame_3 = QtWidgets.QFrame(self.leftMenusubcontainer)
        self.frame_3.setGeometry(QtCore.QRect(0, 590, 261, 81))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.HelpButton = QtWidgets.QPushButton(self.frame_3)
        self.HelpButton.setGeometry(QtCore.QRect(0, 11, 261, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.HelpButton.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icon/icon2/help-circle.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.HelpButton.setIcon(icon4)
        self.HelpButton.setIconSize(QtCore.QSize(20, 20))
        self.HelpButton.setObjectName("HelpButton")
        self.InfoButton = QtWidgets.QPushButton(self.frame_3)
        self.InfoButton.setGeometry(QtCore.QRect(0, 46, 261, 24))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.InfoButton.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon2/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.InfoButton.setIcon(icon5)
        self.InfoButton.setIconSize(QtCore.QSize(20, 20))
        self.InfoButton.setObjectName("InfoButton")
        self.MENUlabel = QtWidgets.QLabel(self.leftMenusubcontainer)
        self.MENUlabel.setGeometry(QtCore.QRect(30, -10, 241, 61))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.MENUlabel.setFont(font)
        self.MENUlabel.setTextFormat(QtCore.Qt.AutoText)
        self.MENUlabel.setIndent(27)
        self.MENUlabel.setObjectName("MENUlabel")
        self.horizontalLayout.addWidget(self.leftMenusubcontainer)
        self.frame_6 = QtWidgets.QFrame(self.centralwidget)
        self.frame_6.setGeometry(QtCore.QRect(260, 0, 851, 671))
        self.frame_6.setToolTipDuration(-1)
        self.frame_6.setStyleSheet("")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.Expense_Frame = QtWidgets.QFrame(self.frame_6)
        self.Expense_Frame.setGeometry(QtCore.QRect(20, 460, 491, 181))
        self.Expense_Frame.setStyleSheet("*{background-color: rgb(28, 41, 72);\n"
"border-radius: 40px;\n"
"pading-left: 20px;}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"QLineEdit{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"}")
        self.Expense_Frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Expense_Frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Expense_Frame.setLineWidth(0)
        self.Expense_Frame.setObjectName("Expense_Frame")
        self.label = QtWidgets.QLabel(self.Expense_Frame)
        self.label.setGeometry(QtCore.QRect(30, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setStyleSheet("color:#fff")
        self.label.setObjectName("label")
        self.group_ = QtWidgets.QComboBox(self.Expense_Frame)
        self.group_.setGeometry(QtCore.QRect(80, 50, 121, 23))
        self.group_.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.group_.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.group_.setFont(font)
        self.group_.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.group_.setStyleSheet("*{color:#fff;\n"
"background-color: rgb(45, 63, 109);\n"
"border-radius:8px;}\n"
"QComboBox{\n"
"    padding-left: 20px;\n"
"\n"
"}\n"
"QComboBox::drop-down {\n"
"    \n"
"    image: url(:/icon/icons/chevron-down.svg);\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: none;\n"
"    padding: 3px\n"
"}\n"
"\n"
"")
        self.group_.setEditable(False)
        self.group_.setIconSize(QtCore.QSize(20, 20))
        self.group_.setObjectName("group_")
        self.group_.addItem("")
        self.group_.addItem("")
        self.lineEdit = QtWidgets.QLineEdit(self.Expense_Frame)
        self.lineEdit.setGeometry(QtCore.QRect(210, 50, 141, 22))
        self.lineEdit.setWhatsThis("")
        self.lineEdit.setStyleSheet("border-bottom: 1px solid;\n"
"border-color:rgba(255, 255, 255,100)\n"
"\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.Expense_Frame)
        self.lineEdit_2.setGeometry(QtCore.QRect(210, 80, 141, 22))
        self.lineEdit_2.setStyleSheet("border-bottom: 1px solid;\n"
"border-color:rgba(255, 255, 255,100)\n"
"\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.Expense_Frame)
        self.pushButton.setGeometry(QtCore.QRect(250, 134, 51, 28))
        self.pushButton.setStyleSheet("QPushButton{\n"
"    border: 1px solid;\n"
"    border-color:#fff;\n"
"    border-radius: 7px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.comboBox_2 = QtWidgets.QComboBox(self.Expense_Frame)
        self.comboBox_2.setGeometry(QtCore.QRect(360, 51, 91, 21))
        self.comboBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.comboBox_2.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.comboBox_2.setStyleSheet("*{color:#fff;\n"
"background-color: rgb(45, 63, 109);\n"
"border-radius:8px;}\n"
"QComboBox{\n"
"    padding-left: 20px;\n"
"\n"
"}\n"
"QComboBox::drop-down {\n"
"    \n"
"    image: url(:/icon/icons/chevron-down.svg);\n"
"    width: 16px;\n"
"    height: 16px;\n"
"    border: none;\n"
"    padding: 3px\n"
"}\n"
"\n"
"")
        self.comboBox_2.setEditable(False)
        self.comboBox_2.setIconSize(QtCore.QSize(20, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.Statistics_frame = QtWidgets.QFrame(self.frame_6)
        self.Statistics_frame.setGeometry(QtCore.QRect(20, 200, 491, 241))
        self.Statistics_frame.setStyleSheet("*{background-color: rgb(28, 41, 72);\n"
"border-radius: 40px;\n"
"pading-left: 20px;}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"QLineEdit{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"}")
        self.Statistics_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Statistics_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Statistics_frame.setLineWidth(0)
        self.Statistics_frame.setObjectName("Statistics_frame")
        self.label_2 = QtWidgets.QLabel(self.Statistics_frame)
        self.label_2.setGeometry(QtCore.QRect(30, 20, 151, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:#fff")
        self.label_2.setObjectName("label_2")
        self.overview_frame = QtWidgets.QFrame(self.frame_6)
        self.overview_frame.setGeometry(QtCore.QRect(20, 70, 491, 111))
        self.overview_frame.setStyleSheet("*{background-color: rgb(28, 41, 72);\n"
"border-radius: 40px;\n"
"pading-left: 20px;}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"QLineEdit{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"}")
        self.overview_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.overview_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.overview_frame.setLineWidth(0)
        self.overview_frame.setObjectName("overview_frame")
        self.label_3 = QtWidgets.QLabel(self.overview_frame)
        self.label_3.setGeometry(QtCore.QRect(30, 20, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:#fff")
        self.label_3.setObjectName("label_3")
        self.Monthly_frame = QtWidgets.QFrame(self.frame_6)
        self.Monthly_frame.setGeometry(QtCore.QRect(540, 70, 221, 221))
        self.Monthly_frame.setStyleSheet("*{background-color: rgb(28, 41, 72);\n"
"border-radius: 40px;\n"
"pading-left: 20px;}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"QLineEdit{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"}")
        self.Monthly_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Monthly_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Monthly_frame.setLineWidth(0)
        self.Monthly_frame.setObjectName("Monthly_frame")
        self.label_5 = QtWidgets.QLabel(self.Monthly_frame)
        self.label_5.setGeometry(QtCore.QRect(30, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:#fff")
        self.label_5.setObjectName("label_5")
        self.History_frame = QtWidgets.QFrame(self.frame_6)
        self.History_frame.setGeometry(QtCore.QRect(540, 310, 221, 331))
        self.History_frame.setStyleSheet("*{background-color: rgb(28, 41, 72);\n"
"border-radius: 40px;\n"
"pading-left: 20px;}\n"
"QComboBox::down-arrow {\n"
"    image:url(:/icon/icons/chevron-down.svg);\n"
"    width: 0;\n"
"}\n"
"QLineEdit{\n"
"border-bottom-color: rgb(255, 255, 255);\n"
"}")
        self.History_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.History_frame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.History_frame.setLineWidth(0)
        self.History_frame.setObjectName("History_frame")
        self.label_4 = QtWidgets.QLabel(self.History_frame)
        self.label_4.setGeometry(QtCore.QRect(30, 10, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:#fff")
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setGeometry(QtCore.QRect(37, 20, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.frame = QtWidgets.QFrame(self.frame_6)
        self.frame.setGeometry(QtCore.QRect(750, 14, 31, 31))
        self.frame.setStyleSheet("QFrame#frame{\n"
"    border-image: url(:/icon/icons/user.svg);\n"
"    border-color: rgb(255, 255, 255);\n"
"    \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.group_.setCurrentIndex(-1)
        self.comboBox_2.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Dashboard.setToolTip(_translate("MainWindow", "Go to home page"))
        self.Dashboard.setText(_translate("MainWindow", "  Dashboard"))
        self.WalletsButton.setToolTip(_translate("MainWindow", "See reports"))
        self.WalletsButton.setText(_translate("MainWindow", "  Wallets"))
        self.CategoriesButton.setToolTip(_translate("MainWindow", "Go to Transaction History Page "))
        self.CategoriesButton.setText(_translate("MainWindow", "  Categories"))
        self.SettingsButton.setToolTip(_translate("MainWindow", "Open settings"))
        self.SettingsButton.setText(_translate("MainWindow", "  Settings"))
        self.HelpButton.setToolTip(_translate("MainWindow", "Ask help"))
        self.HelpButton.setText(_translate("MainWindow", "  Help"))
        self.InfoButton.setToolTip(_translate("MainWindow", "About us"))
        self.InfoButton.setText(_translate("MainWindow", "  Info"))
        self.MENUlabel.setText(_translate("MainWindow", "Expenzio"))
        self.label.setText(_translate("MainWindow", "Add Expenses"))
        self.group_.setItemText(0, _translate("MainWindow", "Item1"))
        self.group_.setItemText(1, _translate("MainWindow", "Item 2"))
        self.pushButton.setText(_translate("MainWindow", "Save"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Item1"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Item 2"))
        self.label_2.setText(_translate("MainWindow", "Expense Statistics"))
        self.label_3.setText(_translate("MainWindow", "Overview"))
        self.label_5.setText(_translate("MainWindow", "This month"))
        self.label_4.setText(_translate("MainWindow", "History"))
        self.label_7.setText(_translate("MainWindow", "  Dashboard"))
import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
