# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'userui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(407, 436)
        Dialog.setMaximumSize(QtCore.QSize(407, 436))
        Dialog.setStyleSheet("#Dialog{background-color:#08508a;}")
        
        # Set up the main vertical layout
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setSpacing(15)
        self.verticalLayout.setObjectName("verticalLayout")
        
        # Add top spacer
        spacerItem = QtWidgets.QSpacerItem(20, 121, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        
        # Horizontal layout for profile picture
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        
        # Profile picture widget
        self.profile_pic = QtWidgets.QLabel(Dialog)
        self.profile_pic.setFixedSize(80, 80)
        self.profile_pic.setStyleSheet("""
            background-color: #013871;
            border-radius: 40px;
            font-size: 36px;
            color: white;
            text-align: center;
            """)
        self.profile_pic.setAlignment(QtCore.Qt.AlignCenter)
        self.profile_pic.setText("J")
        
        self.horizontalLayout.addWidget(self.profile_pic)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        
        # Name label
        self.Name_ = QtWidgets.QLabel(Dialog)
        self.Name_.setObjectName("Name_")
        self.Name_.setAlignment(QtCore.Qt.AlignCenter)  # Align text to center
        self.verticalLayout.addWidget(self.Name_)
        
        # label_3 label
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)  # Align text to center
        self.verticalLayout.addWidget(self.label_3)
        
        # Icons layout
        self.iconLayout = QtWidgets.QHBoxLayout()
        self.iconLayout.setObjectName("iconLayout")
        self.iconLayout.setAlignment(QtCore.Qt.AlignCenter)

        # Create a separator
        self.separator = QtWidgets.QFrame(Dialog)
        self.separator.setFrameShape(QtWidgets.QFrame.HLine)
        self.separator.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.separator.setStyleSheet("color: #4B4B4B;")
        self.verticalLayout.addWidget(self.separator)
        
        # Other profiles label
        self.Salary = QtWidgets.QLabel(Dialog)
        self.Salary.setObjectName("Salary")
        self.Salary.setStyleSheet("color: #8AB4F8;")
        self.Salary.setAlignment(QtCore.Qt.AlignCenter)  # Align text to center
        self.verticalLayout.addWidget(self.Salary)
        
        # Add bottom spacer
        spacerItem3 = QtWidgets.QSpacerItem(20, 121, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Name_.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; color:#ffffff;\">Jopaul</span></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; color:#ffffff;\">jopauljose57@gmail.com</span></p></body></html>"))
        self.Salary.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; color:#8ab4f8;\">Salary:1000</span></p></body></html>"))

import resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
